config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users, controllers: { registrations: 'users/registrations' }
  resources :dogs
  post 'dog_like/:id', to: 'dogs#like', as: :dog_like
  delete 'dog_unlike/:id', to: 'dogs#unlike', as: :dog_unlike
  root to: "dogs#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dog.rb
class Dog < ApplicationRecord
  attribute :recent_likes, :integer
  has_many_attached :images
  belongs_to :owner, optional: true, class_name: 'User', foreign_key: 'user_id'
  has_many :likes
  has_many :users_liked, through: :likes, source: :user
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :dog
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :dogs
  has_many :likes
  has_many :liked_dogs, through: :likes, source: :dog
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/dogs_controller.rb
class DogsController < ApplicationController
  before_action :set_dog, only: [:show, :edit, :update, :destroy, :like, :unlike]

  def like
    Like.create dog: @dog, user: current_user
    respond_to do |format|
      format.html { redirect_to @dog, notice: "You liked #{@dog.name}" }
      format.json { render :show, status: :ok, location: @dog }
    end
  end

  def unlike
    Like.find_by(dog: @dog, user: current_user).destroy
    respond_to do |format|
      format.html { redirect_to @dog, notice: "You unliked #{@dog.name}" }
      format.json { render :show, status: :ok, location: @dog }
    end
  end

  # GET /dogs
  # GET /dogs.json
  def index
    # I tried to accomplish this using solely active record like I would in MySql
    # but after struggling for a while I decided to do the sort in code
    if params[:sorted].present?
      dogsWithLikes = Dog.all.each do | dog |
        count = Like.where(['created_at > ? and dog_id = ? ', 1.hour.ago, dog.id]).count
        dog.recent_likes = count > 0 ? count : 0
      end
      sortedDogs = dogsWithLikes.sort_by(&:recent_likes).reverse
      @dogs = sortedDogs.paginate(:page => params[:page], :per_page=>5)
    else
      @dogs = Dog.paginate(:page => params[:page], :per_page=>5)
    end
  end

  # GET /dogs/1
  # GET /dogs/1.json
  def show
  end

  # GET /dogs/new
  def new
    @dog = Dog.new
  end

  # GET /dogs/1/edit
  def edit
  end

  # POST /dogs
  # POST /dogs.json
  def create
    @dog = Dog.new(dog_params)
    respond_to do |format|
      if @dog.save
        @dog.images.attach(params[:dog][:images]) if params[:dog][:images].present?

        format.html { redirect_to @dog, notice: 'Dog was successfully created.' }
        format.json { render :show, status: :created, location: @dog }
      else
        format.html { render :new }
        format.json { render json: @dog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dogs/1
  # PATCH/PUT /dogs/1.json
  def update
    respond_to do |format|
      if @dog.update(dog_params)
        @dog.images.attach(params[:dog][:images]) if params[:dog][:images].present?

        format.html { redirect_to @dog, notice: 'Dog was successfully updated.' }
        format.json { render :show, status: :ok, location: @dog }
      else
        format.html { render :edit }
        format.json { render json: @dog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dogs/1
  # DELETE /dogs/1.json
  def destroy
    @dog.destroy
    respond_to do |format|
      format.html { redirect_to dogs_url, notice: 'Dog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_dog
    @dog = Dog.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def dog_params
    params.require(:dog).permit(:name, :description, :images, :user_id, :sorted)
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  def create
    super
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dogs_helper.rb
module DogsHelper
end

app/views/dogs/_form.html.erb
<%= simple_form_for @dog do |f| %>
  <%= f.input :name %>
  <%= f.input :description, as: :text %>
  <%= f.file_field :images, multiple: true, accept: 'image/png, image/jpg, image/jpeg, image/gif' %>
  <% if @dog.new_record? %>
    <%= f.hidden_field :user_id, value: current_user.id %>
  <% else %>
    <%= f.collection_select :user_id, User.all, :id, :name, prompt: true, default: '' %>
  <% end %>
  <% if @dog.images.any? %>
    <%= image_tag @dog.images.first %>
  <% end %>

  <%= f.button :submit %>
<% end %>

app/views/dogs/_thumbnail.html.erb
<a class="card" href="<%= url_for(dog) %>">
  <%= image_tag url_for(dog.images.first), class: "dog-photo card-img-top", alt: "Photo of #{dog.name}" %>
  <div class="card-body">
    <h5 class="dog-name"><%= dog.name %></h5>
    <i class="bi bi-heart-fill text-danger"></i>
    <span class="like-counter text-danger"><%= dog.likes.count%></span>
  </div>
</a>

app/views/dogs/edit.html.erb
<div class="row justify-content-center">
    <div class="col-6">
        <h1>Edit Your Dog</h1>
        <%= render partial: 'form' %>
    </div>
</div>

app/views/dogs/index.html.erb
<%# This will sort dogs based on likes within the last hour %>
<%= will_paginate @dogs, :class => "paginate row justify-content-center"%>  
    <div class="row">
        <% @dogs.each_with_index do |dog, i| %>
            <div class="col w-20 d-flex justify-content-center">
                <%= render partial: 'thumbnail', object: dog, as: :dog %>    
            </div>
            <% if (i % 2 != 0) %>
                <div class="col w-20 d-flex justify-content-center">
                    <a class="card">
                        <%= image_tag url_for("/assets/ad.jpg"), class: "dog-photo card-img-top", alt: "Photo of Advertisement" %>
                        <div class="card-body justify-content-center">
                            <h5 class="dog-name"><%= "Get A New Collar Today!" %></h5>
                            <h5 class="dog-name"><%= "Call 1-800-123-4567" %></h5>
                        </div>
                    </a>
                </div>            
            <% end %>
        <% end %>      
    </div>
<%= will_paginate @dogs, :class => "paginate row justify-content-center" %>

app/views/dogs/new.html.erb
<h1>Add Your Dog</h1>
<%= render partial: 'form' %>

app/views/dogs/show.html.erb
<div class="row justify-content-center">
  <div class="col-6">
    <h2>
      <%= @dog.name %>
      <% if @dog.owner == current_user %>
        <i class="bi bi-heart text-danger"></i> <span class="like-counter text-danger"><%= @dog.likes.count%></span>
      <% elsif current_user.likes.pluck(:dog_id).include? @dog.id %>
        <%= link_to '<i class="bi bi-heart-fill text-danger"></i>'.html_safe, dog_unlike_path(@dog), method: :delete %>
        <span class="like-counter text-danger"><%= @dog.likes.count%></span>
      <% else %>
        <%= link_to '<i class="bi bi-heart text-danger"></i>'.html_safe, dog_like_path(@dog), method: :post %>
        <span class="like-counter text-danger"><%= @dog.likes.count%></span>
      <% end %>
    </h2>
      <div id="dogCarousel" class="carousel slide" data-interval="4000" data-ride="carousel">
        <% if @dog.images[1] %>
          <ol class="carousel-indicators">
            <% @dog.images.each_with_index do |photo, n| %>
              <li data-target='#dogCarousel' data-slide-to=<% "#{n}" %> class=<% "#{'active' if n == 0}" %>></li>
            <% end %> 
          </ol>
        <% end %> 
        <div class="carousel-inner" role="listbox">
          <%@dog.images.each_with_index do |pic,i|%>
            <div class="carousel-item <%= "active " if i==0 %>">
              <%= image_tag url_for(pic), :class => "d-block img-fluid" %>
            </div>
          <% end %>
        </div>
        <% if @dog.images[1] %>
          <a class="carousel-control-prev" href="#dogCarousel" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
          </a>
          <a class="carousel-control-next" href="#dogCarousel" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
          </a>
        <% end %> 
      </div>
    <p><%= @dog.description %></p>
    <p><%= @dog.owner ? "Human: #{@dog.owner.name}" : 'This dog is a free spirit, doesn\'t believe in having a human master' %></p>
    <%= link_to "Edit #{@dog.name}'s Profile", edit_dog_path %>
    <br>
    <%= link_to "Delete #{@dog.name}'s Profile", dog_path, method: :delete, data: { confirm: 'Are you sure?' } %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DogProfile</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.0/font/bootstrap-icons.css">
    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbolinks-track": "reload" %>
  </head>

  <body>
    <div id="layout">
      <header class="navbar navbar-expand-lg navbar-light bg-light">
        <%# This link will reset the sort back to normal %>
        <h1><%= link_to 'Dog Profile Demo', root_path %></h1>
        <div class="actions ml-auto">
          <% if current_user %>
            <%= link_to 'Add your dog', new_dog_path %>
            |
            <%= link_to 'Edit Profile', edit_user_registration_path %>
            |
            <%= link_to 'Sign out', destroy_user_session_path, method: :delete %>
          <% else %>
            <%= link_to 'Sign in', new_user_session_path %>
            <%= link_to 'Sign up', new_user_registration_path %>
          <% end %>
        </div>
      </header>
      <div id="main" class="container-fluid">
        <p><%= link_to 'Trending Dogs', dogs_path(sorted: true) %> </p>    
        <div class="notifications">
          <p class="notice"><%= notice %></p>
          <p class="alert"><%= alert %></p>
        </div>
        <%= yield %>
      </div>
      <div class="footer"></div>
    </div>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>